version: 2

sources:
      - name: my_source			## required
        database: dev		## required
        schema: public		## optional
        tables:
          - name: table_test
          - name: departments
          - name: Employees
          - name: hr_employees

      - name: glue_src		## required
        schema: iceberg_schema		## optional
        tables:
          - name: emp_s3_details
          
    